export enum ElementType {
    BUTTON = "BUTTON",
    CHATBOT = "CHATBOT",
    CHATBOT_FEEDBACK = "CHATBOT_FEEDBACK",
    CONDITIONAL_RENDERER = "CONDITIONAL_RENDERER",
    CONTAINER = "CONTAINER",
    DIVIDER = "DIVIDER",
    FREE_RESPONSE = "FREE_RESPONSE",
    IMAGE = "IMAGE",
    MULTIPLE_CHOICE = "MULTIPLE_CHOICE",
    RANDOM_SELECT = "RANDOM_SELECT",
    TABLE = "TABLE",
    TEXT = "TEXT",
    VIDEO = "VIDEO",
    WIDGET = "WIDGET"
}